//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SporcuWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SporcularBilgi
    {
        public int SporcuNo { get; set; }
        public string AdSoyad { get; set; }
        public string Yas { get; set; }
        public string Boy { get; set; }
        public string Kilo { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
    }
}
